name: Build Pebble app

on:
  # Triggers the workflow on push or pull request events for any branch (see commented out `branches` lines for  master branch example)
  push:
    paths:
      - 'src/**'
      - 'resources/**'
      - 'tests/**'
      - 'package.json'
      - 'wscript'
      - '.github/workflows/build-pbw.yaml'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
          fetch-depth: 0
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: js tests
        run: npm install && npm test
      - name: install pebble tool
        run: pip install pebble-tool
      - name: install sdk
        run: yes | pebble sdk install latest
      - name: pebble-build
        run: yes | pebble build
      - name: rename-app
        run: cp build/*.pbw Squire-g${{ env.COMMIT_SHORT_SHA }}.pbw
      - name: generate elf bundle
        run: |
          mkdir elfs
          for elf in build/*/pebble-app.elf; do
            platform=$(basename "$(dirname "$elf")")
            cp "$elf" "elfs/pebble-app-${platform}.elf"
          done
          zip -r elfs.zip elfs
      - name: Upload PBW
        uses: actions/upload-artifact@v4
        with:
          name: Squire PBW
          path: Squire-g${{ env.COMMIT_SHORT_SHA }}.pbw
          if-no-files-found: error
      - name: Upload ELFs
        uses: actions/upload-artifact@v4
        with:
          name: Debug ELFs
          path: elfs.zip
